### ISSUE TITLE
Find reliable way to embed gif for brainlife documentation

### ISSUE THREAD

**Issue by DanNBullock** [brainlife/app-CIT168Parc#4]
https://github.com/brainlife/app-CIT168Parc/blob/main/README.md#L4

Currently, brainlife page doesn't like html embedding method, but the standard markdown method didn't really allow for control of gif size (and resulted in a massive black border).  Figure out an embedding method that (1) allows for gif resolution control and (2) brainlife documentation embedding.

Perhaps @soichih knows of an elegant solution?

**Comment by soichih** [comment]
Are you trying to figure out a way to insert image that works for both github and brainlife.io README page? 

If so, as long as you use an absolute path for your image, it should work.

So try..

```
<img src="https://github.com/brainlife/app-CIT168Parc/raw/main/birdface.gif" alt="birdface" width="232" height="193"/>
```

**Comment by DanNBullock** [comment]
Seems to work (https://brainlife.io/app/5fb2f28a7e8ecb7444aaf372) , thanks!
